# Generated by Django 3.2.13 on 2022-05-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personinfo'),
        ),
    ]
