# Generated by Django 3.2.13 on 2022-04-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personinfo',
            options={'verbose_name': '个人信息表', 'verbose_name_plural': '个人信息表'},
        ),
    ]
